udTreebanks <- function() {
  
  #Annotated pre-trained models for TALL from UD 2.15
  
  language_name <- c(
    "afrikaans", "ancient_greek", "arabic", "armenian", "basque", "belarusian", "bulgarian", 
    "catalan", "chinese", "croatian", "czech", "danish", "dutch", "english", "english", "english", 
    "english", "estonian", "finnish", "french", "galician", "german", "greek", "hebrew", "hindi",
    "hungarian", "indonesian", "irish", "italian", "italian", "korean", "latin", "latvian", 
    "lithuanian", "maltese", "marathi", "north_sami", "norwegian", "old_church_slavonic", "persian",
    "polish", "portuguese", "romanian", "romanian", "russian", "scottish_gaelic", "serbian", 
    "slovak", "slovenian", "spanish", "swedish", "tamil", "telugu", "turkish", "ukrainian", "urdu", 
    "uyghur", "vietnamese", "wolof"
  )
  
  treebank <- c(
    "afribooms", "perseus", "padt", "armtdp", "bdt", "hse", "btb", "ancora", "gsdsimp", "set", 
    "cac", "ddt", "lassysmall", "ewt", "gum", "lines", "partut", "edt", "tdt", "gsd", "ctg", "gsd",
    "gdt", "htb", "hdtb", "szeged", "gsd", "idt", "isdt", "postwita", "kaist", "ittb", "lvtb", 
    "alksnis", "mudt", "ufal", "giella", "bokmaal", "proiel", "seraji", "pdb", "gsd", "nonstandard", 
    "rrt", "syntagrus", "arcosg", "set", "snk", "ssj", "ancora", "talbanken", "ttb", "mtg", "imst", 
    "iu", "udtb", "udt", "vtb", "wtb"
  )
  
  file <- c(
    "af_afribooms", "grc_perseus", "ar_padt", "hy_armtdp", "eu_bdt", "be_hse", "bg_btb", 
    "ca_ancora", "zh_gsdsimp", "hr_set", "cs_cac", "da_ddt", "nl_lassysmall", "en_ewt", "en_gum", 
    "en_lines", "en_partut", "et_edt", "fi_tdt", "fr_gsd", "gl_ctg", "de_gsd", "el_gdt", "he_htb", 
    "hi_hdtb", "hu_szeged", "id_gsd", "ga_idt", "it_isdt", "it_postwita", "ko_kaist", "la_ittb", 
    "lv_lvtb", "lt_alksnis", "mt_mudt", "mr_ufal", "sme_giella", "no_bokmaal", "cu_proiel", 
    "fa_seraji", "pl_pdb", "pt_gsd", "ro_nonstandard", "ro_rrt", "ru_syntagrus", "gd_arcosg", 
    "sr_set", "sk_snk", "sl_ssj", "es_ancora", "sv_talbanken", "ta_ttb", "te_mtg", "tr_imst", 
    "uk_iu", "ur_udtb", "ug_udt", "vi_vtb", "wo_wtb"
  )
  
  description <- c(
    "UD Afrikaans-AfriBooms is a conversion of the AfriBooms Dependency Treebank, originally annotated with a simplified PoS set and dependency relations according to a subset of the Stanford tag set. The corpus consists of public government documents.",
    "This Universal Dependencies Ancient Greek Treebank consists of an automatic",
    "The Arabic-PADT UD treebank is based on the",
    "A Universal Dependencies treebank for Eastern Armenian developed for UD originally by the ArmTDP team led by Marat M. Yavrumyan at the Yerevan State University.",
    "The Basque UD treebank is based on an automatic conversion from part of the Basque Dependency Treebank (BDT), created at the University of the Basque Country by the IXA NLP research group. The treebank consists of 8,993 sentences (121,443 tokens) and covers mainly literary and journalistic texts.",
    "The Belarusian UD treebank is based on a sample of the news texts included in the Belarusian-Russian parallel subcorpus of the Russian National Corpus.",
    "UD_Bulgarian-BTB is based on the HPSG-based BulTreeBank.",
    "Catalan data from the [AnCora](http://clic.ub.edu/corpus/) corpus.",
    "Simplified Chinese Universal Dependencies dataset converted from the GSD (traditional) dataset with manual corrections.",
    "The Croatian UD treebank is based on the extension of the SETimes-HR corpus, the [hr500k](http://hdl.handle.net/11356/1183) corpus.",
    "The UD_Czech-CAC treebank is based on the Czech Academic Corpus 2.0 (CAC).",
    "The Danish UD treebank is a conversion of the Danish Dependency Treebank.",
    "This corpus contains sentences from the Wikipedia section of the Lassy Small Treebank.",
    "A Gold Standard Universal Dependencies Corpus for English.",
    "Universal Dependencies syntax annotations from the GUM corpus (https://gucorpling.org/gum/).",
    "UD English_LinES is the English half of the LinES Parallel Treebank.",
    "UD_English-ParTUT is a conversion of a multilingual parallel treebank developed at the University of Turin.",
    "UD Estonian is a converted version of the Estonian Dependency Treebank (EDT), originally annotated in the Constraint Grammar (CG) annotation scheme, and consisting of genres of fiction, newspaper texts and scientific texts. The treebank contains 30,972 trees, 437,769 tokens.",
    "UD_Finnish-TDT is based on the Turku Dependency Treebank (TDT), a broad-coverage dependency treebank of general Finnish covering numerous genres.",
    "The **UD_French-GSD** was converted in 2015 from the content head version of the universal.",
    "The Galician UD treebank is based on the automatic parsing of the Galician Technical Corpus (http://sli.uvigo.gal/CTG) created at the University of Vigo by the TALG NLP research group.",
    "The German UD is converted from the content head version of the universal.",
    "The Greek UD treebank (UD_Greek-GDT) is derived from the Greek Dependency Treebank.",
    "A Universal Dependencies Corpus for Hebrew.",
    "The Hindi UD treebank is based on the Hindi Dependency Treebank (HDTB).",
    "The Hungarian UD treebank is derived from the Szeged Dependency Treebank (Vincze et al. 2010).",
    "The Indonesian-GSD treebank was originally converted from the content head version of the universal dependency treebank v2.0.",
    "A Universal Dependencies 4910-sentence treebank for modern Irish.",
    "The Italian corpus annotated according to the UD annotation scheme was obtained by conversion from ISDT.",
    "PoSTWITA-UD is a collection of Italian tweets annotated in Universal Dependencies that can be exploited for the training of NLP systems to enhance their performance on social media texts.",
    "The KAIST Korean Universal Dependency Treebank is generated by Chun et al., 2018.",
    "Latin data from the _Index Thomisticus_ Treebank.",
    "Latvian UD Treebank is based on Latvian Treebank (LVTB).",
    "The Lithuanian dependency treebank ALKSNIS v3.0 (Vytautas Magnus University).",
    "MUDT (Maltese Universal Dependencies Treebank) is a manually annotated treebank of Maltese.",
    "UD Marathi is a manually annotated treebank consisting primarily of stories from Wikisource.",
    "This is a North Sámi treebank based on a manually disambiguated and function-labelled gold-standard.",
    "The Norwegian UD treebank is based on the Bokmål section of the Norwegian.",
    "The Old Church Slavonic (OCS) UD treebank is based on canonical Old Church Slavonic data from the PROIEL and TOROT treebanks.",
    "The Persian Universal Dependency Treebank (Seraji) is based on Uppsala Persian Dependency Treebank (UPDT).",
    "The Polish PDB-UD treebank is automatically converted from the Polish Dependency Bank 2.0.",
    "The Brazilian Portuguese UD is converted from the Google Universal Dependency.",
    "The Romanian Non-standard UD treebank (called UAIC-RoDia) is based on UAIC-RoDia Treebank.",
    "The Romanian UD treebank (called RoRefTrees) (Barbu Mititelu et al., 2016) is the reference treebank in UD format for standard Romanian.",
    "Russian data from the SynTagRus corpus.",
    "A treebank of Scottish Gaelic based on the.",
    "The Serbian UD treebank is based on the [SETimes-SR](http://hdl.handle.net/11356/1200) corpus.",
    "The Slovak UD treebank is based on data originally annotated as part of the.",
    "The SSJ treebank is the reference UD treebank for Slovenian.",
    "Spanish data from the [AnCora](http://clic.ub.edu/corpus/) corpus.",
    "The Swedish-Talbanken treebank is based on Talbanken, a treebank developed at Lund University.",
    "The UD Tamil treebank is based on the Tamil Dependency Treebank created at the.",
    "The Telugu UD treebank is created in UD based on manual annotations of sentences from a grammar book.",
    "The UD Turkish Treebank, also called the IMST-UD Treebank, is a semi-automatic conversion of the IMST Treebank.",
    "Gold standard Universal Dependencies corpus for Ukrainian.",
    "The Urdu Universal Dependency Treebank was automatically converted from Urdu Dependency Treebank (UDTB).",
    "The Uyghur UD treebank is based on the Uyghur Dependency Treebank (UDT).",
    "The Vietnamese UD treebank is a conversion of the constituent treebank created in the VLSP project.",
    "UD_Wolof-WTB is a natively manual developed treebank for Wolof."
  )

  folder <- paste0("UD_", language_name, "-", treebank)  # Generazione dinamica

  hub_page_link <- c(
    "https://universaldependencies.org/treebanks/af_afribooms/index.html",
    "https://universaldependencies.org/treebanks/grc_perseus/index.html",
    "https://universaldependencies.org/treebanks/ar_padt/index.html",
    "https://universaldependencies.org/treebanks/hy_armtdp/index.html",
    "https://universaldependencies.org/treebanks/eu_bdt/index.html",
    "https://universaldependencies.org/treebanks/be_hse/index.html",
    "https://universaldependencies.org/treebanks/bg_btb/index.html",
    "https://universaldependencies.org/treebanks/ca_ancora/index.html",
    "https://universaldependencies.org/treebanks/zh_gsdsimp/index.html",
    "https://universaldependencies.org/treebanks/hr_set/index.html",
    "https://universaldependencies.org/treebanks/cs_cac/index.html",
    "https://universaldependencies.org/treebanks/da_ddt/index.html",
    "https://universaldependencies.org/treebanks/nl_lassysmall/index.html",
    "https://universaldependencies.org/treebanks/en_ewt/index.html",
    "https://universaldependencies.org/treebanks/en_gum/index.html",
    "https://universaldependencies.org/treebanks/en_lines/index.html",
    "https://universaldependencies.org/treebanks/en_partut/index.html",
    "https://universaldependencies.org/treebanks/et_edt/index.html",
    "https://universaldependencies.org/treebanks/fi_tdt/index.html",
    "https://universaldependencies.org/treebanks/fr_gsd/index.html",
    "https://universaldependencies.org/treebanks/gl_ctg/index.html",
    "https://universaldependencies.org/treebanks/de_gsd/index.html",
    "https://universaldependencies.org/treebanks/el_gdt/index.html",
    "https://universaldependencies.org/treebanks/he_htb/index.html",
    "https://universaldependencies.org/treebanks/hi_hdtb/index.html",
    "https://universaldependencies.org/treebanks/hu_szeged/index.html",
    "https://universaldependencies.org/treebanks/id_gsd/index.html",
    "https://universaldependencies.org/treebanks/ga_idt/index.html",
    "https://universaldependencies.org/treebanks/it_isdt/index.html",
    "https://universaldependencies.org/treebanks/it_postwita/index.html",
    "https://universaldependencies.org/treebanks/ko_kaist/index.html",
    "https://universaldependencies.org/treebanks/la_ittb/index.html",
    "https://universaldependencies.org/treebanks/lv_lvtb/index.html",
    "https://universaldependencies.org/treebanks/lt_alksnis/index.html",
    "https://universaldependencies.org/treebanks/mt_mudt/index.html",
    "https://universaldependencies.org/treebanks/mr_ufal/index.html",
    "https://universaldependencies.org/treebanks/sme_giella/index.html",
    "https://universaldependencies.org/treebanks/no_bokmaal/index.html",
    "https://universaldependencies.org/treebanks/cu_proiel/index.html",
    "https://universaldependencies.org/treebanks/fa_seraji/index.html",
    "https://universaldependencies.org/treebanks/pl_pdb/index.html",
    "https://universaldependencies.org/treebanks/pt_gsd/index.html",
    "https://universaldependencies.org/treebanks/ro_nonstandard/index.html",
    "https://universaldependencies.org/treebanks/ro_rrt/index.html",
    "https://universaldependencies.org/treebanks/ru_syntagrus/index.html",
    "https://universaldependencies.org/treebanks/gd_arcosg/index.html",
    "https://universaldependencies.org/treebanks/sr_set/index.html",
    "https://universaldependencies.org/treebanks/sk_snk/index.html",
    "https://universaldependencies.org/treebanks/sl_ssj/index.html",
    "https://universaldependencies.org/treebanks/es_ancora/index.html",
    "https://universaldependencies.org/treebanks/sv_talbanken/index.html",
    "https://universaldependencies.org/treebanks/ta_ttb/index.html",
    "https://universaldependencies.org/treebanks/te_mtg/index.html",
    "https://universaldependencies.org/treebanks/tr_imst/index.html",
    "https://universaldependencies.org/treebanks/uk_iu/index.html",
    "https://universaldependencies.org/treebanks/ur_udtb/index.html",
    "https://universaldependencies.org/treebanks/ug_udt/index.html",
    "https://universaldependencies.org/treebanks/vi_vtb/index.html",
    "https://universaldependencies.org/treebanks/wo_wtb/index.html"
  )
  
  contributors <- c(
    "Peter Dirix, Liesbeth Augustinus, Daniel van Niekerk",
    "Giuseppe G. A. Celano, Daniel Zeman",
    "Daniel Zeman, Zdeněk Žabokrtský, Shadi Saleh",
    "Marat M. Yavrumyan",
    "Maria Jesus Aranzabe, Aitziber Atutxa, Kepa Bengoetxea, Arantza Diaz de Ilarraza, Iakes Goenaga, Koldo Gojenola, Larraitz Uria",
    "Olga Lyashevskaya, Angelika Peljak-Łapińska, Daria Petrova, Yana Shishkina",
    "Kiril Simov, Petya Osenova, Martin Popel",
    "Héctor Martínez Alonso, Elena Pascual, Daniel Zeman",
    "Peng Qi, Koichi Yasuoka",
    "Željko Agić, Nikola Ljubešić, Daniel Zeman",
    "Barbora Hladká, Daniel Zeman",
    "Anders Johannsen, Héctor Martínez Alonso, Barbara Plank",
    "Gosse Bouma, Gertjan van Noord",
    "Natalia Silveira, Timothy Dozat, Christopher Manning, Sebastian Schuster, Ethan Chi, John Bauer, Miriam Connor, Marie-Catherine de Marneffe, Nathan Schneider, Sam Bowman, Hanzhi Zhu, Daniel Galbraith, John Bauer",
    "Siyao Peng, Amir Zeldes",
    "Lars Ahrenberg",
    "Cristina Bosco, Manuela Sanguinetti",
    "Kadri Muischnek, Kaili Müürisep, Tiina Puolakainen, Andriela Rääbis, Liisi Torga",
    "Filip Ginter, Jenna Kanerva, Veronika Laippala, Niko Miekka, Anna Missilä, Stina Ojala, Sampo Pyysalo",
    "Marie-Catherine de Marneffe, Bruno Guillaume, Ryan McDonald, Alane Suhr, Joakim Nivre, Matias Grioni, Carly Dickerson, Guy Perrier",
    "Xavier Gómez Guinovart",
    "Slav Petrov, Wolfgang Seeker, Ryan McDonald, Joakim Nivre, Daniel Zeman, Adriane Boyd",
    "Prokopis Prokopidis",
    "Yoav Goldberg, Reut Tsarfaty, Amir More, Shoval Sadde, Victoria Basmov, Yuval Pinter",
    "Riyaz Ahmad Bhat, Daniel Zeman",
    "Richárd Farkas, Katalin Simkó, Zsolt Szántó, Viktor Varga, Veronika Vincze",
    "Ryan McDonald, Joakim Nivre, Daniel Zeman, Septina Dian Larasati, Ika Alfina",
    "Teresa Lynn, Jennifer Foster, Sarah McGuinness, Abigail Walsh, Jason Phelan, Kevin Scannell",
    "Cristina Bosco, Alessandro Lenci, Simonetta Montemagni, Maria Simi",
    "Cristina Bosco, Manuela Sanguinetti",
    "Jinho Choi, Na-Rae Han, Jena Hwang, Jayeol Chun",
    "Marco Passarotti, Marinella Testori, Daniel Zeman, Berta González Saavedra, Flavio Massimiliano Cecchini",
    "Lauma Pretkalniņa, Laura Rituma, Gunta Nešpore-Bērzkalne, Baiba Saulīte, Artūrs Znotiņš, Normunds Grūzītis",
    "Andrius Utka, Erika Rimkutė, Agnė Bielinskienė, Jolanta Kovalevskaitė, Loïc Boizou, Gabrielė Aleksandravičiūtė, Kristina Brokaitė, Daniel Zeman, Natalia Perkova, Bernadeta Griciūtė",
    "Slavomír Čéplö, Daniel Zeman",
    "Vinit Ravishankar",
    "Trond Trosterud, Lene Antonsen, Francis Tyers",
    "Lilja Øvrelid, Fredrik Jørgensen, Petter Hohle, Ingerid Løyning Dale, Per Erik Solberg, Andre Kåsen",
    "Dag Haug",
    "Mojgan Seraji, Filip Ginter, Joakim Nivre, Martin Popel, Daniel Zeman",
    "Alina Wróblewska, Daniel Zeman, Jan Mašek, Rudolf Rosa",
    "Alexandre Rademaker, Ryan McDonald, Joakim Nivre, Daniel Zeman, Fabricio Chalub, Carlos Ramisch, Juan Belieni, Vanessa Berwanger Wille, Rodrigo Pintucci",
    "Cătălina Mărănduc, Cenel-Augusto Perez, Victoria Bobicev, Cătălin Mititelu, Florinel Hociung, Valentin Roșca, Roman Untilov, Petru Rebeja",
    "Verginica Barbu Mititelu, Elena Irimia, Cenel-Augusto Perez, Radu Ion, Radu Simionescu, Martin Popel",
    "Kira Droganova, Olga Lyashevskaya, Daniel Zeman",
    "Colin Batchelor",
    "Tanja Samardžić, Nikola Ljubešić",
    "Katarína Gajdošová, Mária Šimková, Daniel Zeman",
    "Kaja Dobrovoljc, Tomaž Erjavec, Simon Krek",
    "Héctor Martínez Alonso, Daniel Zeman",
    "Joakim Nivre, Aaron Smith, Victor Norrman",
    "Loganathan Ramasamy, Daniel Zeman",
    "Taraka Rama, Sowmya Vajjala",
    "Utku Türk, Şaziye Betül Özateş, Büşra Marşan, Salih Furkan Akkurt, Çağrı Çöltekin, Gülşen Cebiroğlu Eryiğit, Memduh Gökırmak, Hüner Kaşıkara, Umut Sulubacak, Francis Tyers",
    "Natalia Kotsyba, Bohdan Moskalevskyi, Mykhailo Romanenko",
    "Riyaz Ahmad Bhat, Daniel Zeman",
    "Marhaba Eli, Daniel Zeman, Francis Tyers",
    "Lương Nguyễn Thị, Linh Hà Mỹ, Phương Lê Hồng, Huyền Nguyễn Thị Minh",
    "Bamba Dione"
  )
  
  df <- data.frame(
    language_name = language_name,
    treebank = treebank,
    contributors = contributors,
    description = description,
    file = file,
    folder = folder,
    hub_page_link = hub_page_link
  )
  
  return(df)
}


