// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_chisq
double cpp_chisq(const IntegerVector& T1, const IntegerVector& T2, const IntegerVector& Tsum);
RcppExport SEXP _tall_cpp_chisq(SEXP T1SEXP, SEXP T2SEXP, SEXP TsumSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type T1(T1SEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type T2(T2SEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type Tsum(TsumSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_chisq(T1, T2, Tsum));
    return rcpp_result_gen;
END_RCPP
}
// cpp_split_tab
List cpp_split_tab(const IntegerMatrix& tab, const IntegerVector& indices);
RcppExport SEXP _tall_cpp_split_tab(SEXP tabSEXP, SEXP indicesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type tab(tabSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type indices(indicesSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_split_tab(tab, indices));
    return rcpp_result_gen;
END_RCPP
}
// cpp_switch_docs
NumericVector cpp_switch_docs(const IntegerMatrix& tab1, const IntegerMatrix& tab2);
RcppExport SEXP _tall_cpp_switch_docs(SEXP tab1SEXP, SEXP tab2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type tab1(tab1SEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type tab2(tab2SEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_switch_docs(tab1, tab2));
    return rcpp_result_gen;
END_RCPP
}
// calc_reciprocal_sum_cpp
NumericVector calc_reciprocal_sum_cpp(List ngram_words, CharacterVector word_freq_names, NumericVector word_freq_values);
RcppExport SEXP _tall_calc_reciprocal_sum_cpp(SEXP ngram_wordsSEXP, SEXP word_freq_namesSEXP, SEXP word_freq_valuesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type ngram_words(ngram_wordsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type word_freq_names(word_freq_namesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type word_freq_values(word_freq_valuesSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_reciprocal_sum_cpp(ngram_words, word_freq_names, word_freq_values));
    return rcpp_result_gen;
END_RCPP
}
// count_lexical_cpp
IntegerVector count_lexical_cpp(List ngram_pos, CharacterVector lexical_pos);
RcppExport SEXP _tall_count_lexical_cpp(SEXP ngram_posSEXP, SEXP lexical_posSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type ngram_pos(ngram_posSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type lexical_pos(lexical_posSEXP);
    rcpp_result_gen = Rcpp::wrap(count_lexical_cpp(ngram_pos, lexical_pos));
    return rcpp_result_gen;
END_RCPP
}
// generate_ngrams_cpp
List generate_ngrams_cpp(List sentences_terms, List sentences_pos, int max_ngram, CharacterVector lexical_pos);
RcppExport SEXP _tall_generate_ngrams_cpp(SEXP sentences_termsSEXP, SEXP sentences_posSEXP, SEXP max_ngramSEXP, SEXP lexical_posSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type sentences_terms(sentences_termsSEXP);
    Rcpp::traits::input_parameter< List >::type sentences_pos(sentences_posSEXP);
    Rcpp::traits::input_parameter< int >::type max_ngram(max_ngramSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type lexical_pos(lexical_posSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_ngrams_cpp(sentences_terms, sentences_pos, max_ngram, lexical_pos));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tall_cpp_chisq", (DL_FUNC) &_tall_cpp_chisq, 3},
    {"_tall_cpp_split_tab", (DL_FUNC) &_tall_cpp_split_tab, 2},
    {"_tall_cpp_switch_docs", (DL_FUNC) &_tall_cpp_switch_docs, 2},
    {"_tall_calc_reciprocal_sum_cpp", (DL_FUNC) &_tall_calc_reciprocal_sum_cpp, 3},
    {"_tall_count_lexical_cpp", (DL_FUNC) &_tall_count_lexical_cpp, 2},
    {"_tall_generate_ngrams_cpp", (DL_FUNC) &_tall_generate_ngrams_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_tall(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
