# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_chisq <- function(T1, T2, Tsum) {
    .Call('_tall_cpp_chisq', PACKAGE = 'tall', T1, T2, Tsum)
}

cpp_split_tab <- function(tab, indices) {
    .Call('_tall_cpp_split_tab', PACKAGE = 'tall', tab, indices)
}

cpp_switch_docs <- function(tab1, tab2) {
    .Call('_tall_cpp_switch_docs', PACKAGE = 'tall', tab1, tab2)
}

calc_reciprocal_sum_cpp <- function(ngram_words, word_freq_names, word_freq_values) {
    .Call('_tall_calc_reciprocal_sum_cpp', PACKAGE = 'tall', ngram_words, word_freq_names, word_freq_values)
}

count_lexical_cpp <- function(ngram_pos, lexical_pos) {
    .Call('_tall_count_lexical_cpp', PACKAGE = 'tall', ngram_pos, lexical_pos)
}

generate_ngrams_cpp <- function(sentences_terms, sentences_pos, max_ngram) {
    .Call('_tall_generate_ngrams_cpp', PACKAGE = 'tall', sentences_terms, sentences_pos, max_ngram)
}

